package com.example;

public enum MessageType {
    INFMSG_DEFAULT_SPETIAL_CHARS,
    INFMSG_IGNORE_SPETIAL_CHAR_OPERATION,
    ERRMSG_INPUT_NON_SPECIAL_CHAR,
    ERRMSG_NUMBER_FORMAT_EXCEPTION,
    ERRMSG_NO_SUCH_ALGORITHM_EXCEPTION,
    ERRMSG_ARRAY_INDEX_OUT_OF_BOUNDS_EXCEPTION,
    ERRMSG_OVER_RANGE_VALUE_EXCEPTION,
    ERRMSG_OVER_PASSWORD_LENGTH_EXCEPTION,
    ERRMSG_UNEXPECTED_ARGUMENTS_EXCEPTION,
    ERRMSG_INPUT_INCOMPATIBLE_VALUE;
}
